// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lcu} from '../models';

export function Reload():Promise<void>;

export function Setup():Promise<boolean>;

export function Summoner():Promise<lcu.SunnmonerInfo>;

export function ToggleAccept():Promise<void>;
