// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function Setup() {
  return window['go']['main']['App']['Setup']();
}

export function Summoner() {
  return window['go']['main']['App']['Summoner']();
}

export function ToggleAccept() {
  return window['go']['main']['App']['ToggleAccept']();
}
